### ISSUE TITLE
yum-multithread breaks the ability to install rpm directly via yum

### ISSUE THREAD

**Issue by dzabel** [mjschultz/yum-multithread#1]
yum-multithread enabled:

yum localinstall rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm
Loaded plugins: fastestmirror, multithread, priorities
Setting up Local Package Process
Examining rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm: rpmforge-release-0.5.2-2.el6.rf.x86_64
Marking rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm to be installed
Loading mirror speeds from cached hostfile
- base: ftp.halifax.rwth-aachen.de
- extras: mirror.de.leaseweb.net
- updates: mirror.de.leaseweb.net
  Resolving Dependencies
  --> Running transaction check
  ---> Package rpmforge-release.x86_64 0:0.5.2-2.el6.rf will be installed
  --> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package                            Arch                     Version                             Repository                                                 Size

Installing:
 rpmforge-release                   x86_64                   0.5.2-2.el6.rf                      /rpmforge-release-0.5.2-2.el6.rf.x86_64                    13 k
# Transaction Summary

Install       1 Package(s)

Total size: 13 k
Installed size: 13 k
Is this ok [y/N]: y
Downloading Packages:

Error getting repository data for /rpmforge-release-0.5.2-2.el6.rf.x86_64, repository not found

---

same machine yum-multithread enabled=0

yum localinstall rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
- base: ftp.halifax.rwth-aachen.de
- extras: mirror.de.leaseweb.net
- updates: mirror.de.leaseweb.net
  Setting up Install Process
  rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm                                                                                                |  12 kB     00:00
  Examining /var/tmp/yum-root-FUJv9V/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm: rpmforge-release-0.5.2-2.el6.rf.x86_64
  Marking /var/tmp/yum-root-FUJv9V/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm to be installed
  Resolving Dependencies
  --> Running transaction check
  ---> Package rpmforge-release.x86_64 0:0.5.2-2.el6.rf will be installed
  --> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package                            Arch                     Version                             Repository                                                 Size

Installing:
 rpmforge-release                   x86_64                   0.5.2-2.el6.rf                      /rpmforge-release-0.5.2-2.el6.rf.x86_64                    13 k
# Transaction Summary

Install       1 Package(s)

Total size: 13 k
Installed size: 13 k
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : rpmforge-release-0.5.2-2.el6.rf.x86_64                                                                                                        1/1
  Verifying  : rpmforge-release-0.5.2-2.el6.rf.x86_64                                                                                                        1/1

Installed:
  rpmforge-release.x86_64 0:0.5.2-2.el6.rf

Complete!

**Comment by mjschultz** [comment]
Thanks for the report, I'll look into it this weekend.

I believe the next release of yum should include parallel download support natively, per [this announcement](http://lists.fedoraproject.org/pipermail/devel/2012-May/167122.html). It looks like it is planned for RHEL 7, though you may be able to find a backport to RHEL 6 (or its derivatives) which is likely to be a more thorough treatment of parallel downloading than this plugin.
